"""add is_active to parking_lots

Revision ID: add_is_active_to_parking_lots
Revises: remove_business_license_address
Create Date: 2026-07-29 01:56:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_is_active_to_parking_lots'
down_revision: Union[str, None] = 'remove_business_license_address'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_lots', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parking_lots', 'is_active')
    # ### end Alembic commands ###
