"""add is_verified to users

Revision ID: add_is_verified_to_users
Revises: remove_features_from_subscription_plans
Create Date: 2026-07-27 11:11:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_is_verified_to_users'
down_revision: Union[str, None] = 'remove_features_from_subscription_plans'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True, server_default='1'))

    # Backfill: mark all existing users as verified so they are not locked out.
    op.execute("UPDATE users SET is_verified = 1 WHERE is_verified IS NULL")

    # Now make the column non-nullable.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_verified', nullable=False, server_default='1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_verified')
    # ### end Alembic commands ###
