"""add_rate_per_hour_to_parking_lots_and_pending_session_status

Revision ID: d6b210fd2506
Revises: 02d08b938ea8
Create Date: 2026-07-30 02:45:00.822138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b210fd2506'
down_revision: Union[str, None] = '02d08b938ea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_lots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate_per_hour', sa.Float(), nullable=True))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_index('ix_parking_lots_address')
        batch_op.drop_index('ix_parking_lots_type')
        batch_op.drop_column('longitude')
        batch_op.drop_column('address')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_lots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.FLOAT(), nullable=True))
        batch_op.create_index('ix_parking_lots_type', ['type'], unique=False)
        batch_op.create_index('ix_parking_lots_address', ['address'], unique=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('rate_per_hour')

    # ### end Alembic commands ###
