"""move created_by from users to parking_staff

Revision ID: move_created_by
Revises: remove_position
Create Date: 2026-07-29 19:12:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'move_created_by'
down_revision: Union[str, None] = 'remove_position'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove created_by from users table (batch mode recreates table, FK dropped automatically)
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    # Add created_by to parking_staff table
    with op.batch_alter_table('parking_staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_parking_staff_created_by_users', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove created_by from parking_staff table
    with op.batch_alter_table('parking_staff', schema=None) as batch_op:
        batch_op.drop_constraint('fk_parking_staff_created_by_users', type_='foreignkey')
        batch_op.drop_column('created_by')

    # Add created_by back to users table
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


