"""remove position from parking_staff

Revision ID: remove_position
Revises: remove_employee_code
Create Date: 2026-07-29 03:24:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'remove_position'
down_revision: Union[str, None] = 'remove_employee_code'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_staff', schema=None) as batch_op:
        batch_op.drop_column('position')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###
