"""remove business_license and address from parking_owners

Revision ID: remove_business_license_address
Revises: 83055a782cfd
Create Date: 2026-07-29 01:42:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'remove_business_license_address'
down_revision: Union[str, None] = '83055a782cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if business_license column exists before dropping it
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('parking_owners')]
    
    if 'business_license' in columns:
        op.drop_column('parking_owners', 'business_license')
    
    if 'address' in columns:
        op.drop_column('parking_owners', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_owners', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('parking_owners', sa.Column('business_license', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###
