"""rename otp used to is_used

Revision ID: rename_otp_used_to_is_used
Revises: rename_otp_verified_to_used
Create Date: 2026-07-28 00:35:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'rename_otp_used_to_is_used'
down_revision: Union[str, None] = 'rename_otp_verified_to_used'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER COLUMN directly, so we need to recreate the table
    op.execute("CREATE TABLE otps_new (id INTEGER NOT NULL, email VARCHAR(255) NOT NULL, code VARCHAR(10) NOT NULL, expires_at DATETIME NOT NULL, created_at DATETIME, is_used BOOLEAN NOT NULL DEFAULT 0, PRIMARY KEY (id))")
    
    # Copy data from old table to new table, converting used to is_used
    op.execute("INSERT INTO otps_new (id, email, code, expires_at, created_at, is_used) SELECT id, email, code, expires_at, created_at, CASE WHEN used = 1 THEN 1 ELSE 0 END FROM otps")
    
    # Create indexes on new table
    op.execute("CREATE INDEX ix_otps_new_id ON otps_new (id)")
    op.execute("CREATE INDEX ix_otps_new_email ON otps_new (email)")
    
    # Drop old table
    op.execute("DROP TABLE otps")
    
    # Rename new table to old name
    op.execute("ALTER TABLE otps_new RENAME TO otps")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate the old table structure with 'used' column
    op.execute("CREATE TABLE otps_new (id INTEGER NOT NULL, email VARCHAR(255) NOT NULL, code VARCHAR(10) NOT NULL, expires_at DATETIME NOT NULL, created_at DATETIME, used INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (id))")
    
    # Copy data from current table to new table, converting is_used back to used
    op.execute("INSERT INTO otps_new (id, email, code, expires_at, created_at, used) SELECT id, email, code, expires_at, created_at, CASE WHEN is_used = 1 THEN 1 ELSE 0 END FROM otps")
    
    # Create indexes on new table
    op.execute("CREATE INDEX ix_otps_new_id ON otps_new (id)")
    op.execute("CREATE INDEX ix_otps_new_email ON otps_new (email)")
    
    # Drop current table
    op.execute("DROP TABLE otps")
    
    # Rename new table to old name
    op.execute("ALTER TABLE otps_new RENAME TO otps")
    # ### end Alembic commands ###
