"""rename otp verified to used

Revision ID: rename_otp_verified_to_used
Revises: add_is_verified_to_users
Create Date: 2026-07-28 00:16:00.000000

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'rename_otp_verified_to_used'
down_revision: Union[str, None] = 'add_is_verified_to_users'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.alter_column('verified', new_column_name='used')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.alter_column('used', new_column_name='verified')

    # ### end Alembic commands ###